// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Accordion: typeof import('./components/common/Accordion.vue')['default']
    BackgroundPattern: typeof import('./components/common/BackgroundPattern.vue')['default']
    Badge: typeof import('./components/common/Badge.vue')['default']
    Btn: typeof import('./components/common/Btn.vue')['default']
    Collapse: typeof import('./components/common/Collapse.vue')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    Expand: typeof import('./components/common/Expand.vue')['default']
    FavoriteCell: typeof import('./components/Favorites/FavoriteCell.vue')['default']
    FavoriteList: typeof import('./components/Favorites/FavoriteList.vue')['default']
    FavoritesList: typeof import('./components/Favorites/FavoritesList.vue')['default']
    Img: typeof import('./components/common/Img.vue')['default']
    InfiniteScroll: typeof import('./components/common/InfiniteScroll.vue')['default']
    JrnwnLogo: typeof import('./components/JrnwnLogo.vue')['default']
    NotificationArea: typeof import('./components/common/NotificationArea.vue')['default']
    PokeballSpinner: typeof import('./components/MainModule/PokeballSpinner.vue')['default']
    PokemonAvatar: typeof import('./components/MainModule/PokemonAvatar.vue')['default']
    PokemonCell: typeof import('./components/MainModule/PokemonCell.vue')['default']
    RightDrawer: typeof import('./components/common/RightDrawer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TimeoutBar: typeof import('./components/common/TimeoutBar.vue')['default']
    TypeBadge: typeof import('./components/MainModule/TypeBadge.vue')['default']
    VuedexLogo: typeof import('./components/MainModule/VuedexLogo.vue')['default']
  }
}
